// frontend/src/components/SupportHoursForm.tsx
import { type FC, useCallback, useEffect, useMemo, useState } from "react";
import timezones from "timezones-list";
import type { SupportHoursData } from "@/types";
import Button from "@/components/Button";
import Select from "@/components/Select";
import ColourSelect from "@/components/ColourSelect";
import TextInput from "@/components/TextInput";
import Textarea from "@/components/Textarea";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBriefcase, faCopy, faTimes } from "@fortawesome/free-solid-svg-icons";

const DAYS_OF_WEEK = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

const timezoneOptions = [
  { label: "UTC (+00:00)", key: "UTC" },
  ...timezones.map((tz) => ({ label: tz.label, key: tz.tzCode })),
];

function formatTime(timeString: string): string {
  if (!timeString) return "09:00";
  if (/^\d{2}:\d{2}$/.test(timeString)) return timeString;
  if (/^\d{2}:\d{2}:\d{2}$/.test(timeString)) return timeString.substring(0, 5);
  return "09:00";
}

function colourIntToHex(colour: number): string {
  return `#${colour.toString(16).padStart(6, "0")}`;
}

function hexToColourInt(hex: string): number {
  return parseInt(hex.replace("#", ""), 16);
}

interface HoursState {
  day_of_week: number;
  enabled: boolean;
  start_time: string;
  end_time: string;
}

interface SupportHoursFormProps {
  value: SupportHoursData | null;
  onChange: (data: SupportHoursData | null) => void;
}

const SupportHoursForm: FC<SupportHoursFormProps> = ({ value, onChange }) => {
  const [timezone, setTimezone] = useState("Europe/London");
  const [hours, setHours] = useState<HoursState[]>(() =>
    DAYS_OF_WEEK.map((_, index) => ({
      day_of_week: index,
      enabled: false,
      start_time: "09:00",
      end_time: "17:00",
    })),
  );
  const [outOfHoursBehaviour, setOutOfHoursBehaviour] = useState<
    "block_creation" | "allow_with_warning"
  >("block_creation");
  const [outOfHoursTitle, setOutOfHoursTitle] = useState("");
  const [outOfHoursMessage, setOutOfHoursMessage] = useState("");
  const [outOfHoursColour, setOutOfHoursColour] = useState("#FC3F35");
  const [currentTimeDisplay, setCurrentTimeDisplay] = useState("");

  // Load initial data from value prop
  useEffect(() => {
    if (!value) return;
    if (value.timezone) setTimezone(value.timezone);
    if (value.out_of_hours_behaviour) setOutOfHoursBehaviour(value.out_of_hours_behaviour);
    if (value.out_of_hours_title) setOutOfHoursTitle(value.out_of_hours_title);
    if (value.out_of_hours_message) setOutOfHoursMessage(value.out_of_hours_message);
    if (value.out_of_hours_colour) setOutOfHoursColour(colourIntToHex(value.out_of_hours_colour));

    if (value.hours && value.hours.length > 0) {
      setHours((prev) => {
        const updated = [...prev];
        for (const item of value.hours) {
          if (item.day_of_week >= 0 && item.day_of_week < 7) {
            updated[item.day_of_week] = {
              day_of_week: item.day_of_week,
              enabled: item.enabled,
              start_time: formatTime(item.start_time),
              end_time: formatTime(item.end_time),
            };
          }
        }
        return updated;
      });
    }
    // Only run on mount
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const hasAnyEnabled = useMemo(() => hours.some((h) => h.enabled), [hours]);

  // Update current time display
  useEffect(() => {
    const updateTime = () => {
      try {
        const formatter = new Intl.DateTimeFormat("en-GB", {
          timeZone: timezone,
          hour: "2-digit",
          minute: "2-digit",
          hour12: false,
          weekday: "long",
        });
        const parts = formatter.formatToParts(new Date());
        const weekday = parts.find((p) => p.type === "weekday")?.value || "";
        const hour = parts.find((p) => p.type === "hour")?.value || "00";
        const minute = parts.find((p) => p.type === "minute")?.value || "00";
        const tzInfo = timezoneOptions.find((t) => t.key === timezone);
        const utcOffset = tzInfo ? tzInfo.label.match(/\(([^)]+)\)/)?.[1] || "" : "";
        setCurrentTimeDisplay(
          `It is currently ${hour}:${minute} on ${weekday} in ${timezone}${utcOffset ? ` (${utcOffset})` : ""}`,
        );
      } catch {
        setCurrentTimeDisplay(`Timezone: ${timezone}`);
      }
    };
    updateTime();
    const interval = setInterval(updateTime, 30000);
    return () => clearInterval(interval);
  }, [timezone]);

  const emitChange = useCallback(
    (
      newHours: HoursState[],
      newTimezone: string,
      newBehaviour: "block_creation" | "allow_with_warning",
      newTitle: string,
      newMessage: string,
      newColour: string,
    ) => {
      const enabledHours = newHours.filter((h) => h.enabled);
      if (enabledHours.length === 0) {
        onChange(null);
        return;
      }
      onChange({
        timezone: newTimezone,
        hours: enabledHours.map((h) => ({
          day_of_week: h.day_of_week,
          start_time: `${h.start_time}:00`,
          end_time: `${h.end_time}:00`,
          enabled: true,
        })),
        out_of_hours_behaviour: newBehaviour,
        out_of_hours_title: newTitle,
        out_of_hours_message: newMessage,
        out_of_hours_colour: hexToColourInt(newColour),
      });
    },
    [onChange],
  );

  const handleTimezoneChange = (tz: string | null) => {
    if (!tz) return;
    setTimezone(tz);
    emitChange(
      hours,
      tz,
      outOfHoursBehaviour,
      outOfHoursTitle,
      outOfHoursMessage,
      outOfHoursColour,
    );
  };

  const handleDayToggle = (index: number) => {
    const updated = [...hours];
    updated[index] = { ...updated[index], enabled: !updated[index].enabled };
    if (updated[index].enabled) {
      updated[index].start_time = "09:00";
      updated[index].end_time = "17:00";
    }
    setHours(updated);
    emitChange(
      updated,
      timezone,
      outOfHoursBehaviour,
      outOfHoursTitle,
      outOfHoursMessage,
      outOfHoursColour,
    );
  };

  const handleTimeChange = (index: number, field: "start_time" | "end_time", value: string) => {
    const updated = [...hours];
    updated[index] = { ...updated[index], [field]: value };

    // Validate: if start >= end, adjust end
    if (field === "start_time" && updated[index].start_time >= updated[index].end_time) {
      const [startHour, startMin] = updated[index].start_time.split(":").map(Number);
      let endHour = startHour + 1;
      if (endHour >= 24) endHour = 23;
      updated[index].end_time =
        `${String(endHour).padStart(2, "0")}:${String(startMin).padStart(2, "0")}`;
    }

    setHours(updated);
    emitChange(
      updated,
      timezone,
      outOfHoursBehaviour,
      outOfHoursTitle,
      outOfHoursMessage,
      outOfHoursColour,
    );
  };

  const handleBehaviourChange = (val: string | null) => {
    if (!val) return;
    const behaviour = val as "block_creation" | "allow_with_warning";
    setOutOfHoursBehaviour(behaviour);
    emitChange(hours, timezone, behaviour, outOfHoursTitle, outOfHoursMessage, outOfHoursColour);
  };

  const handleTitleChange = (val: string) => {
    const clamped = val.slice(0, 100);
    setOutOfHoursTitle(clamped);
    emitChange(hours, timezone, outOfHoursBehaviour, clamped, outOfHoursMessage, outOfHoursColour);
  };

  const handleMessageChange = (val: string) => {
    const clamped = val.slice(0, 500);
    setOutOfHoursMessage(clamped);
    emitChange(hours, timezone, outOfHoursBehaviour, outOfHoursTitle, clamped, outOfHoursColour);
  };

  const handleColourChange = (val: string) => {
    setOutOfHoursColour(val);
    emitChange(hours, timezone, outOfHoursBehaviour, outOfHoursTitle, outOfHoursMessage, val);
  };

  const copyToWeekdays = () => {
    const monday = hours[1];
    if (!monday.enabled) return;
    const updated = [...hours];
    for (let i = 2; i <= 5; i++) {
      updated[i] = {
        day_of_week: i,
        enabled: true,
        start_time: monday.start_time,
        end_time: monday.end_time,
      };
    }
    setHours(updated);
    emitChange(
      updated,
      timezone,
      outOfHoursBehaviour,
      outOfHoursTitle,
      outOfHoursMessage,
      outOfHoursColour,
    );
  };

  const setBusinessHours = () => {
    const updated = hours.map((h, i) => ({
      ...h,
      enabled: i >= 1 && i <= 5,
      start_time: "09:00",
      end_time: "17:00",
    }));
    setHours(updated);
    emitChange(
      updated,
      timezone,
      outOfHoursBehaviour,
      outOfHoursTitle,
      outOfHoursMessage,
      outOfHoursColour,
    );
  };

  const clearAll = () => {
    const updated = DAYS_OF_WEEK.map((_, index) => ({
      day_of_week: index,
      enabled: false,
      start_time: "09:00",
      end_time: "17:00",
    }));
    setHours(updated);
    emitChange(
      updated,
      timezone,
      outOfHoursBehaviour,
      outOfHoursTitle,
      outOfHoursMessage,
      outOfHoursColour,
    );
  };

  return (
    <div className="flex flex-col gap-4">
      <Select
        label="Timezone"
        value={timezone}
        options={timezoneOptions}
        onChange={handleTimezoneChange}
      />

      {/* Info notices */}
      <div className="flex flex-wrap gap-3">
        <div className="flex items-center gap-2 px-3 py-2 bg-white/5 rounded-md text-sm text-gray-300">
          <span className="text-blue-400">&#127760;</span>
          <span>{currentTimeDisplay}</span>
        </div>
        {!hasAnyEnabled ? (
          <div className="flex items-center gap-2 px-3 py-2 bg-white/5 rounded-md text-sm text-gray-300">
            <span className="text-green-400">&#10003;</span>
            <span>Panel is available 24/7 (no restrictions)</span>
          </div>
        ) : (
          <div className="flex items-center gap-2 px-3 py-2 bg-white/5 rounded-md text-sm text-gray-300">
            <span className="text-amber-400">&#9432;</span>
            <span>Panel availability is restricted to configured hours</span>
          </div>
        )}
      </div>

      {/* Days grid */}
      <div className="flex flex-col gap-0.5 bg-black/20 rounded-lg p-0.5">
        {DAYS_OF_WEEK.map((day, index) => (
          <div
            key={day}
            className={`flex items-center justify-between px-4 py-3 rounded-md ${
              hours[index].enabled ? "bg-[#2d3142]" : "bg-[#2a2a2a]"
            } hover:brightness-110 transition-all`}
          >
            <button
              type="button"
              className="flex flex-row items-center gap-3 cursor-pointer select-none"
              onClick={() => handleDayToggle(index)}
              title={hours[index].enabled ? `Disable ${day}` : `Enable ${day}`}
            >
              <div
                className={`w-5 h-5 shrink-0 rounded border flex items-center justify-center transition-colors ${hours[index].enabled ? "bg-blue-600 border-blue-600" : "bg-gray-700 border-neutral-600"}`}
              >
                {hours[index].enabled && (
                  <svg
                    className="w-3 h-3 text-white"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={3}
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                )}
              </div>
              <span className="font-medium text-sm uppercase tracking-wide text-white/90">
                {day}
              </span>
            </button>

            <div className="flex items-center">
              {hours[index].enabled ? (
                <div className="flex items-center gap-3">
                  <input
                    type="time"
                    value={hours[index].start_time}
                    onChange={(e) => handleTimeChange(index, "start_time", e.target.value)}
                    className="px-2.5 py-1.5 border border-white/10 rounded bg-black/30 text-white/90 text-sm font-mono focus:outline-none focus:border-green-500"
                    aria-label={`Start time for ${day}`}
                  />
                  <span className="text-white/40 text-xs">to</span>
                  <input
                    type="time"
                    value={hours[index].end_time}
                    onChange={(e) => handleTimeChange(index, "end_time", e.target.value)}
                    className="px-2.5 py-1.5 border border-white/10 rounded bg-black/30 text-white/90 text-sm font-mono focus:outline-none focus:border-green-500"
                    aria-label={`End time for ${day}`}
                  />
                </div>
              ) : hasAnyEnabled ? (
                <span className="px-3.5 py-1.5 rounded text-xs font-medium uppercase tracking-wide bg-red-500/15 text-red-400">
                  Closed
                </span>
              ) : (
                <span className="px-3.5 py-1.5 rounded text-xs font-medium uppercase tracking-wide bg-sky-400/15 text-sky-400">
                  24/7
                </span>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Out-of-hours settings */}
      {hasAnyEnabled && (
        <div className="flex flex-col gap-3 p-4 bg-black/20 rounded-lg">
          <Select
            label="Out-of-hours behaviour"
            value={outOfHoursBehaviour}
            options={[
              { label: "Block ticket creation", key: "block_creation" },
              { label: "Allow with warning", key: "allow_with_warning" },
            ]}
            onChange={handleBehaviourChange}
          />
          <p className="text-xs text-white/50">
            {outOfHoursBehaviour === "block_creation"
              ? "Users will not be able to open tickets outside of support hours."
              : "Users can still open tickets outside of support hours, but will see a warning message."}
          </p>

          <ColourSelect
            label="Embed Colour"
            value={outOfHoursColour}
            onChange={handleColourChange}
          />

          <TextInput
            label="Custom out-of-hours title"
            placeholder="This panel is currently closed"
            value={outOfHoursTitle}
            onChange={handleTitleChange}
          />

          <div className="flex flex-col">
            <Textarea
              label="Custom out-of-hours message"
              value={outOfHoursMessage}
              onChange={handleMessageChange}
              max={500}
            />
          </div>
        </div>
      )}

      {/* Quick action buttons */}
      <div className="flex flex-wrap gap-2 pt-2 border-t border-white/10">
        <Button
          variant="outline"
          onClick={copyToWeekdays}
          disabled={!hours[1].enabled}
          title="Copy Monday's hours to Tuesday through Friday"
          className="gap-2 text-sm font-medium"
        >
          <FontAwesomeIcon icon={faCopy} className="text-xs" />
          Copy to weekdays
        </Button>
        <Button
          variant="outline"
          onClick={setBusinessHours}
          title="Set standard business hours (Mon-Fri 09:00-17:00)"
          className="gap-2 text-sm font-medium"
        >
          <FontAwesomeIcon icon={faBriefcase} className="text-xs" />
          Business hours
        </Button>
        <Button
          variant="outline"
          onClick={clearAll}
          title={hasAnyEnabled ? "Remove all restrictions (return to 24/7)" : "Clear settings"}
          className="gap-2 text-sm font-medium text-red-400 hover:text-red-300"
        >
          <FontAwesomeIcon icon={faTimes} className="text-xs" />
          {hasAnyEnabled ? "Set 24/7" : "Clear all"}
        </Button>
      </div>
    </div>
  );
};

export default SupportHoursForm;

// frontend/src/components/manage/SupportHoursForm.svelte
<script>
    import { createEventDispatcher, onMount, tick } from "svelte";
    import BetaAlert from "../BetaAlert.svelte";
    import SearchSelect from "../form/SearchSelect.svelte";
    import timezones from "timezones-list";
    import Colour from "../form/Colour.svelte";
    import Dropdown from "../form/Dropdown.svelte";
    import Textarea from "../form/Textarea.svelte";
    import Input from "../form/Input.svelte";
    import { colourToInt, intToColour } from "../../js/util";

    const timezoneList = [
        {
            label: "UTC",
            tzCode: "UTC",
            name: "UTC",
            utc: "+00:00",
        },
        ...timezones,
    ];

    export let data = [];

    const dispatch = createEventDispatcher();
    const daysOfWeek = [
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
    ];

    let timezone = "Europe/London";
    let currentTimeDisplay = "";
    let outOfHoursBehaviour = "block_creation";
    let outOfHoursTitle = "";
    let outOfHoursMessage = "";
    let tempColour = "#FC3F35";
    let hours = daysOfWeek.map((_, index) => ({
        day_of_week: index,
        enabled: false,
        start_time: "09:00",
        end_time: "17:00",
    }));

    // Update current time display whenever timezone changes
    $: {
        updateCurrentTimeDisplay(timezone);
    }

    function updateCurrentTimeDisplay(tz) {
        const now = new Date();
        const tzData = timezoneList.find((t) => t.tzCode === tz);

        if (!tzData) {
            currentTimeDisplay = "Invalid timezone";
            return;
        }

        try {
            // Create formatter for the timezone
            const formatter = new Intl.DateTimeFormat("en-US", {
                timeZone: tz,
                hour: "2-digit",
                minute: "2-digit",
                second: "2-digit",
                hour12: false,
                weekday: "long",
            });

            const parts = formatter.formatToParts(now);
            const timeStr = formatter.format(now);

            // Extract time components
            const weekday =
                parts.find((p) => p.type === "weekday")?.value || "";
            const hour = parts.find((p) => p.type === "hour")?.value || "00";
            const minute =
                parts.find((p) => p.type === "minute")?.value || "00";

            // Format: "It is currently HH:MM on Monday in America/New_York (UTC-05:00)"
            const offset = tzData.utc;
            currentTimeDisplay = `It is currently ${hour}:${minute} on ${weekday} in ${tz} (${offset})`;
        } catch (e) {
            currentTimeDisplay = `Timezone: ${tz}`;
        }
    }

    onMount(() => {
        // Handle new response format with timezone and hours
        if (data && typeof data === "object") {
            // New format: { timezone, hours: [...] }
            if (data.timezone) {
                timezone = data.timezone;
            }

            if (data.out_of_hours_behaviour) {
                outOfHoursBehaviour = data.out_of_hours_behaviour;
            }

            if (data.out_of_hours_title) {
                outOfHoursTitle = data.out_of_hours_title;
            }

            if (data.out_of_hours_message) {
                outOfHoursMessage = data.out_of_hours_message;
            }

            if (data.out_of_hours_colour) {
                tempColour = intToColour(data.out_of_hours_colour);
            }

            const hoursArray = data.hours || data;
            if (
                hoursArray &&
                Array.isArray(hoursArray) &&
                hoursArray.length > 0
            ) {
                hoursArray.forEach((item) => {
                    if (item.day_of_week >= 0 && item.day_of_week < 7) {
                        hours[item.day_of_week] = {
                            day_of_week: item.day_of_week,
                            enabled: item.enabled,
                            start_time: formatTime(item.start_time),
                            end_time: formatTime(item.end_time),
                        };
                    }
                });
            }
        }
    });

    function formatTime(timeString) {
        if (!timeString) return "09:00";
        // If it's already in HH:MM format, return as is
        if (timeString.match(/^\d{2}:\d{2}$/)) {
            return timeString;
        }
        // If it's in HH:MM:SS format, remove seconds
        if (timeString.match(/^\d{2}:\d{2}:\d{2}$/)) {
            return timeString.substring(0, 5);
        }
        return "09:00";
    }

    function handleDayToggle(index) {
        if (!hours[index].enabled) {
            // Set default hours when enabling
            hours[index].start_time = "09:00";
            hours[index].end_time = "17:00";
        }
        emitChange();
    }

    function updateColour() {
        emitChange();
    }

    function validateTimeRange(index) {
        const start = hours[index].start_time;
        const end = hours[index].end_time;

        if (start && end && start >= end) {
            // If start is after end, set end to 1 hour after start
            const [startHour, startMin] = start.split(":").map(Number);
            let endHour = startHour + 1;
            if (endHour >= 24) endHour = 23;
            hours[index].end_time =
                `${String(endHour).padStart(2, "0")}:${String(startMin).padStart(2, "0")}`;
        }
        emitChange();
    }

    function copyToAllWeekdays() {
        const mondayHours = hours[1]; // Monday is index 1
        if (!mondayHours.enabled) return;

        // Copy to Tuesday through Friday (indices 2-5)
        for (let i = 2; i <= 5; i++) {
            hours[i] = {
                day_of_week: i,
                enabled: true,
                start_time: mondayHours.start_time,
                end_time: mondayHours.end_time,
            };
        }
        hours = hours; // Trigger reactivity
        emitChange();
    }

    function setBusinessHours() {
        // Set Monday through Friday 9:00-17:00
        for (let i = 1; i <= 5; i++) {
            hours[i] = {
                day_of_week: i,
                enabled: true,
                start_time: "09:00",
                end_time: "17:00",
            };
        }
        // Weekend closed
        hours[0].enabled = false;
        hours[6].enabled = false;

        hours = hours; // Trigger reactivity
        emitChange();
    }

    function clearAll() {
        hours = daysOfWeek.map((_, index) => ({
            day_of_week: index,
            enabled: false,
            start_time: "09:00",
            end_time: "17:00",
        }));
        emitChange();
    }

    function emitChange() {
        const enabledHours = hours
            .filter((h) => h.enabled)
            .map((h) => ({
                day_of_week: h.day_of_week,
                start_time: `${h.start_time}:00`, // Add seconds for backend
                end_time: `${h.end_time}:00`,
                enabled: true,
            }));
        dispatch("change", {
            timezone,
            hours: enabledHours,
            out_of_hours_behaviour: outOfHoursBehaviour,
            out_of_hours_title: outOfHoursTitle,
            out_of_hours_message: outOfHoursMessage,
            out_of_hours_colour: colourToInt(tempColour),
        });
    }

    // Export function to get current data
    export function getData() {
        const enabledHours = hours
            .filter((h) => h.enabled)
            .map((h) => ({
                day_of_week: h.day_of_week,
                start_time: `${h.start_time}:00`,
                end_time: `${h.end_time}:00`,
                enabled: true,
            }));
        return {
            timezone,
            hours: enabledHours,
            out_of_hours_behaviour: outOfHoursBehaviour,
            out_of_hours_title: outOfHoursTitle,
            out_of_hours_message: outOfHoursMessage,
            out_of_hours_colour: colourToInt(tempColour),
        };
    }
</script>

<div class="support-hours-container">
    <div class="form-group">
        <SearchSelect
            bind:value={timezone}
            options={timezoneList.map((tz) => ({
                label: tz.label,
                value: tz.tzCode,
            }))}
            label="Timezone"
            placeholder="Search timezones..."
            on:change={emitChange}
        />
        <div class="info-section">
            <div class="current-time-notice">
                <i class="fas fa-globe"></i>
                <span>{currentTimeDisplay}</span>
            </div>
            {#if !hours.some((h) => h.enabled)}
                <div class="default-notice">
                    <i class="fas fa-check-circle"></i>
                    <span>Panel is available 24/7 (no restrictions)</span>
                </div>
            {:else}
                <div class="restriction-notice">
                    <i class="fas fa-info-circle"></i>
                    <span
                        >Panel availability is restricted to configured hours</span
                    >
                </div>
            {/if}
        </div>
        <BetaAlert style="width: 100%" />
        <div class="days-container">
            {#each daysOfWeek as day, index}
                <div class="day-row" class:enabled={hours[index].enabled}>
                    <div class="day-info">
                        <div class="day-checkbox">
                            <input
                                type="checkbox"
                                id="day-{index}"
                                bind:checked={hours[index].enabled}
                                on:change={() => handleDayToggle(index)}
                            />
                            <label for="day-{index}" class="day-label">
                                {day}
                            </label>
                        </div>
                    </div>

                    <div class="time-section">
                        {#if hours[index].enabled}
                            <div class="time-inputs">
                                <input
                                    type="time"
                                    bind:value={hours[index].start_time}
                                    on:change={() => validateTimeRange(index)}
                                    class="time-input"
                                    aria-label="Start time for {day}"
                                />
                                <span class="time-separator">to</span>
                                <input
                                    type="time"
                                    bind:value={hours[index].end_time}
                                    on:change={() => validateTimeRange(index)}
                                    class="time-input"
                                    aria-label="End time for {day}"
                                />
                            </div>
                        {:else if hours.some((h) => h.enabled)}
                            <div class="status-label closed">Closed</div>
                        {:else}
                            <div class="status-label open-24-7">24/7</div>
                        {/if}
                    </div>
                </div>
            {/each}
        </div>

        {#if hours.some((h) => h.enabled)}
            <div class="settings-section">
                <div class="setting-group">
                    <Dropdown
                        label="Out-of-hours behaviour"
                        bind:value={outOfHoursBehaviour}
                    >
                        <option value="block_creation"
                            >Block ticket creation</option
                        >
                        <option value="allow_with_warning"
                            >Allow with warning</option
                        >
                    </Dropdown>
                    <span class="setting-description">
                        {#if outOfHoursBehaviour === "block_creation"}
                            Users will not be able to open tickets outside of
                            support hours.
                        {:else}
                            Users can still open tickets outside of support
                            hours, but will see a warning message.
                        {/if}
                    </span>
                </div>

                <div class="settings-group">
                    <Input
                        label="Custom out-of-hours title"
                        bind:value={outOfHoursTitle}
                        on:input={emitChange}
                        placeholder="This panel is currently closed"
                        maxlength="100"
                    />
                </div>

                <div class="setting-group">
                    <Textarea
                        label="Custom out-of-hours message"
                        bind:value={outOfHoursMessage}
                        on:input={emitChange}
                        placeholder="Please try again during our support hours"
                        maxlength="500"
                        rows="3"
                    />
                    <span class="setting-char-count">
                        {outOfHoursMessage.length}/500
                    </span>
                </div>

                <div class="setting-group">
                    <Colour
                        label="Embed Colour"
                        on:change={updateColour}
                        bind:value={tempColour}
                    />
                </div>
            </div>
        {/if}

        <div class="actions">
            <button
                class="action-button"
                on:click={copyToAllWeekdays}
                disabled={!hours[1].enabled}
                title="Copy Monday's hours to Tuesday through Friday"
            >
                <i class="fas fa-copy"></i>
                Copy to weekdays
            </button>
            <button
                class="action-button"
                on:click={setBusinessHours}
                title="Set standard business hours (Mon-Fri 9:00-17:00)"
            >
                <i class="fas fa-briefcase"></i>
                Business hours
            </button>
            <button
                class="action-button secondary"
                on:click={clearAll}
                title={hours.some((h) => h.enabled)
                    ? "Remove all restrictions (return to 24/7)"
                    : "Clear settings"}
            >
                <i class="fas fa-times"></i>
                {hours.some((h) => h.enabled) ? "Set 24/7" : "Clear all"}
            </button>
        </div>
    </div>
</div>

<style>
    .support-hours-container {
        width: 100%;
    }

    .form-group {
        display: flex;
        flex-direction: column;
        gap: 16px;
    }

    .info-section {
        display: flex;
        gap: 12px;
        flex-wrap: wrap;
    }

    .current-time-notice,
    .default-notice,
    .restriction-notice {
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 8px 12px;
        background: rgba(255, 255, 255, 0.05);
        border-radius: 6px;
        font-size: 13px;
        color: rgba(255, 255, 255, 0.7);
    }

    .current-time-notice i {
        color: #995df3;
    }

    .default-notice i {
        color: #81c784;
    }

    .restriction-notice i {
        color: #ffb74d;
    }

    .days-container {
        display: flex;
        flex-direction: column;
        gap: 2px;
        background: rgba(0, 0, 0, 0.2);
        border-radius: 8px;
        padding: 2px;
    }

    .day-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 12px 16px;
        background: #2a2a2a;
        border-radius: 6px;
        transition: all 0.2s ease;
    }

    .day-row.enabled {
        background: #2d3142;
    }

    .day-row:hover {
        background: #323232;
    }

    .day-row.enabled:hover {
        background: #353849;
    }

    .day-info {
        display: flex;
        align-items: center;
        gap: 12px;
        flex: 1;
    }

    .day-checkbox {
        display: flex;
        align-items: center;
        gap: 12px;
    }

    .day-checkbox input[type="checkbox"] {
        width: 18px;
        height: 18px;
        cursor: pointer;
        accent-color: #66bb6a;
    }

    .day-label {
        font-weight: 500;
        font-size: 14px;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        color: rgba(255, 255, 255, 0.9);
        cursor: pointer;
        user-select: none;
        min-width: 100px;
    }

    .time-section {
        display: flex;
        align-items: center;
    }

    .time-inputs {
        display: flex;
        align-items: center;
        gap: 12px;
    }

    .time-input {
        padding: 6px 10px;
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 4px;
        background: rgba(0, 0, 0, 0.3);
        color: rgba(255, 255, 255, 0.9);
        font-size: 14px;
        font-family: "SF Mono", "Monaco", "Inconsolata", "Fira Code", monospace;
        transition: all 0.2s ease;
    }

    .time-input:hover {
        border-color: rgba(255, 255, 255, 0.2);
        background: rgba(0, 0, 0, 0.4);
    }

    .time-input:focus {
        outline: none;
        border-color: #66bb6a;
        background: rgba(0, 0, 0, 0.5);
    }

    .time-separator {
        color: rgba(255, 255, 255, 0.4);
        font-size: 13px;
    }

    .status-label {
        padding: 6px 14px;
        border-radius: 4px;
        font-size: 13px;
        font-weight: 500;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }

    .status-label.closed {
        background: rgba(244, 67, 54, 0.15);
        color: #ef5350;
    }

    .status-label.open-24-7 {
        background: rgba(79, 195, 247, 0.15);
        color: #4fc3f7;
    }

    .settings-section {
        display: flex;
        flex-direction: column;
        gap: 16px;
        padding: 16px;
        background: rgba(0, 0, 0, 0.2);
        border-radius: 8px;
    }

    .setting-group {
        display: flex;
        flex-direction: column;
        gap: 6px;
    }

    .setting-label {
        font-weight: 500;
        font-size: 13px;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        color: rgba(255, 255, 255, 0.7);
    }

    .setting-description {
        font-size: 12px;
        color: rgba(255, 255, 255, 0.5);
    }

    .setting-textarea {
        padding: 8px 12px;
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 6px;
        background: rgba(0, 0, 0, 0.3);
        color: rgba(255, 255, 255, 0.9);
        font-size: 14px;
        font-family: inherit;
        resize: vertical;
        transition: all 0.2s ease;
    }

    .setting-textarea:hover {
        border-color: rgba(255, 255, 255, 0.2);
        background: rgba(0, 0, 0, 0.4);
    }

    .setting-textarea:focus {
        outline: none;
        border-color: #66bb6a;
        background: rgba(0, 0, 0, 0.5);
    }

    .setting-textarea::placeholder {
        color: rgba(255, 255, 255, 0.3);
    }

    .setting-char-count {
        font-size: 11px;
        color: rgba(255, 255, 255, 0.4);
        text-align: right;
    }

    .actions {
        display: flex;
        gap: 8px;
        padding-top: 8px;
        border-top: 1px solid rgba(255, 255, 255, 0.1);
    }

    .action-button {
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 8px 14px;
        background: rgba(255, 255, 255, 0.08);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 6px;
        color: rgba(255, 255, 255, 0.8);
        font-size: 13px;
        font-weight: 500;
        cursor: pointer;
        transition: all 0.2s ease;
    }

    .action-button:hover:not(:disabled) {
        background: rgba(255, 255, 255, 0.12);
        border-color: rgba(255, 255, 255, 0.2);
        color: rgba(255, 255, 255, 0.95);
    }

    .action-button.secondary {
        background: rgba(244, 67, 54, 0.1);
        border-color: rgba(244, 67, 54, 0.2);
        color: #ef5350;
    }

    .action-button.secondary:hover:not(:disabled) {
        background: rgba(244, 67, 54, 0.15);
        border-color: rgba(244, 67, 54, 0.3);
    }

    .action-button:disabled {
        opacity: 0.4;
        cursor: not-allowed;
    }

    .action-button i {
        font-size: 12px;
    }

    @media (max-width: 768px) {
        .info-section {
            flex-direction: column;
        }

        .default-notice {
            width: 100%;
        }

        .day-row {
            flex-direction: column;
            align-items: flex-start;
            gap: 12px;
        }

        .time-section {
            width: 100%;
        }

        .time-inputs {
            width: 100%;
            justify-content: space-between;
        }

        .actions {
            flex-direction: column;
        }

        .action-button {
            width: 100%;
            justify-content: center;
        }
    }
</style>
