// frontend/src/components/discord/container/Button.tsx
import { isSafeUrl } from "@/lib/url";
import { emojiUrl } from "@/lib/discord-cdn";

interface ButtonProps {
  button_style?: number;
  custom_id?: string;
  emoji?: { name: string; id?: string; animated?: boolean };
  label?: string;
  url?: string;
  className?: string;
  disabled?: boolean;
}

function convertButtonStyle(style?: number): string {
  switch (style) {
    case 1:
      return "text-white bg-[#4752c4]";
    case 2:
      return "bg-[#4f545c] text-white";
    case 3:
      return "text-white bg-[#2d7d46]";
    case 4:
      return "text-white bg-[#a12d2f]";
    case 5:
      return "bg-[#4f545c] text-white no-underline";
    default:
      return "";
  }
}

export default function Button({
  button_style,
  custom_id,
  emoji,
  label,
  url,
  className,
  disabled,
}: ButtonProps) {
  const baseClasses = `inline-flex items-center justify-center align-middle px-4 h-8 min-w-15 rounded text-sm font-medium select-none transition-colors duration-150 ${disabled ? "opacity-50 cursor-not-allowed" : "cursor-pointer"}`;
  const styleClasses = convertButtonStyle(button_style);

  if (button_style === 5 && url && isSafeUrl(url)) {
    return (
      <a
        href={url}
        className={`${baseClasses} ${styleClasses} ${className}`}
        data-custom-id={custom_id || ""}
        target="_blank"
        rel="noopener noreferrer"
      >
        {emoji &&
          (emoji.id && emoji.id !== "0" ? (
            <img
              src={emojiUrl(emoji.id, emoji.animated ?? false)}
              alt={emoji.name}
              className="w-4.5 h-4.5 mr-2 object-contain"
            />
          ) : (
            <span className="mr-2">{emoji.name}</span>
          ))}
        {label || ""}&nbsp;<i className="fas fa-external-link-alt"></i>
      </a>
    );
  }

  return (
    <div className={`${baseClasses} ${styleClasses} ${className}`} data-custom-id={custom_id || ""}>
      {emoji &&
        (emoji.id && emoji.id !== "0" ? (
          <img
            src={emojiUrl(emoji.id, emoji.animated ?? false)}
            alt={emoji.name}
            className="w-4.5 h-4.5 mr-2 object-contain"
          />
        ) : (
          <span className="mr-2">{emoji.name}</span>
        ))}
      {label || ""}
    </div>
  );
}

// frontend/src/components/transcript/Button.svelte
{#if button_style === 5 && url}
    <a href={url} class="discord-button {convertButtonStyle(button_style)}" data-custom-id={custom_id || ''} target="_blank" rel="noopener noreferrer">
        {#if emoji}
            <span class="emoji">{emoji.name}</span>
        {/if}
        {label || ''}&nbsp;<i class="fas fa-external-link-alt"></i>
    </a>
{:else}
    <div class="discord-button {convertButtonStyle(button_style)}" data-custom-id={custom_id || ''}>
        {#if emoji}
            <span class="emoji">{emoji.name}</span>
        {/if}
        {label || ''}
    </div>
{/if}

<script>
    export let button_style;
    export let custom_id;
    export let emoji;
    export let label;
    export let url;

    function convertButtonStyle(style) {
        switch (style) {
            case 1:
                return 'button-primary';
            case 2:
                return 'button-secondary';
            case 3:
                return 'button-success';
            case 4:
                return 'button-danger';
            case 5:
                return 'button-link';
            default:
                return '';
        }
    }
</script>
<style>
    
.discord-button {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 2px 16px;
    min-width: 60px;
    min-height: 32px;
    border-radius: 3px;
    font-size: 14px;
    font-weight: 500;
    user-select: none;
    line-height: 16px;
    transition: background-color 0.17s ease, color 0.17s ease;
    cursor: pointer;
}

/* Button styles */
.button-primary {
    background-color: var(--discord-button);
    color: white;
}

.button-primary:hover {
    background-color: #4752c4;
}

.button-secondary {
    background-color: #4f545c;
    color: white;
}

.button-secondary:hover {
    background-color: #686d73;
}

.button-success {
    background-color: var(--discord-green);
    color: white;
}

.button-success:hover {
    background-color: #2d7d46;
}

.button-danger {
    background-color: var(--discord-red);
    color: white;
}

.button-danger:hover {
    background-color: #a12d2f;
}

.button-link {
    background-color: #4f545c;
    color: white;
    text-decoration: none;
}

.button-link:hover {
    background-color: #686d73;
}

.button-disabled {
    opacity: 0.5;
    cursor: not-allowed;
}

.discord-button .emoji {
    width: 18px;
    height: 18px;
    margin-right: 8px;
    vertical-align: -4px;
}
</style>
