// frontend/src/components/discord/container/Container.tsx
import type { GuildChannel, GuildRole, User } from "@/types";
import DiscordContent from "../DiscordContent";
import ActionRow from "./ActionRow";
import Button from "./Button";
import MediaGallery from "./MediaGallery";
import Section from "./Section";

interface ContainerProps {
  entities?: {
    users: Record<string, User>;
    channels: Record<string, GuildChannel>;
    roles: Record<string, GuildRole>;
  };
  component?: {
    spoiler?: boolean;
    accent_color?: string;
    type?: number;
    emoji?: { name: string };
    label?: string;
    components?: Array<{
      type: number;
      style?: number;
      custom_id?: string;
      emoji?: { name: string; id?: string; animated?: boolean };
      label?: string;
      url?: string;
      components?: Array<{
        type: number;
        style?: number;
        custom_id?: string;
        emoji?: { name: string };
        label?: string;
        placeholder?: string;
        options?: Array<{
          value: string;
          label: string;
          description?: string;
          emoji?: { name: string };
        }>;
        content?: string;
      }>;
      content?: string;
      items?: Array<{
        spoiler?: boolean;
        media?: {
          url: string;
        };
      }>;
      accessory?: {
        type: number;
        media?: {
          url: string;
        };
        style?: number;
        custom_id?: string;
        emoji?: { name: string };
        label?: string;
        url?: string;
      } | null;
    }>;
  };
}

export default function Container({ component = {}, entities }: ContainerProps) {
  const borderColor = component.accent_color || "transparent";
  const spoilerClass = component.spoiler ? "blur hover:blur-none" : "";

  return (
    <div
      className={`bg-[#242429] rounded p-3 my-1 max-w-130 w-full ${spoilerClass}`}
      style={{ borderLeft: `6px solid ${borderColor}` }}
    >
      {component.components && component.components.length > 0 && (
        <>
          {component.components.map((subcomponent, index) => {
            if (subcomponent.type === 1) {
              return <ActionRow key={index} components={subcomponent.components} />;
            } else if (subcomponent.type === 2) {
              return (
                <Button
                  key={index}
                  button_style={subcomponent.style}
                  custom_id={subcomponent.custom_id}
                  emoji={subcomponent.emoji}
                  label={subcomponent.label}
                  url={subcomponent.url}
                />
              );
            } else if (subcomponent.type === 9) {
              return (
                <Section
                  key={index}
                  entities={entities}
                  textComponents={subcomponent.components
                    ?.filter((comp) => comp.content)
                    .map((comp) => ({ content: comp.content! }))}
                  accessory={subcomponent.accessory}
                />
              );
            } else if (subcomponent.type === 10) {
              return (
                <DiscordContent
                  key={index}
                  content={subcomponent.content || ""}
                  entities={entities}
                />
              );
            } else if (subcomponent.type === 12) {
              return <MediaGallery key={index} items={subcomponent.items} />;
            } else if (subcomponent.type === 13) {
              return (
                <div key={index} className="my-1">
                  <input
                    type="file"
                    disabled
                    aria-label="File upload"
                    title="File upload"
                    className="opacity-50 cursor-not-allowed"
                  />
                </div>
              );
            } else if (subcomponent.type === 14) {
              return <div key={index} className="h-px w-full bg-gray-600/50 my-1 max-w-130" />;
            } else {
              return (
                <div
                  key={index}
                  className="border border-dashed border-gray-500 rounded p-2 text-gray-500 text-xs italic my-1"
                >
                  Unknown Component Type: {subcomponent.type}
                </div>
              );
            }
          })}
        </>
      )}
    </div>
  );
}

// frontend/src/components/transcript/Container.svelte
<div class="component-container {component.spoiler ? 'spoiler' : ''}" style="border-left: 6px solid {component.accent_color || 'transparent'};">
    {#if component.components && component.components.length > 0}
        {#each component.components as subcomponent}
            {#if subcomponent.type == 1}
                <ActionRow components={subcomponent.components} />
            {:else if component.type == 2} <!-- Button -->
                <Button
                    button_style={5}
                    emoji={component.emoji}
                    label={component.label}
            />
            {:else if subcomponent.type == 9}
                <Section textComponents={subcomponent.components} accessory={subcomponent.accessory} />
            {:else if subcomponent.type == 10}
                <div class="discord-text-component">
                    {@html subcomponent.content
                    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') // Bold
                    .replace(/^### (.*)$/gm, '<h3>$1</h3>') // Header 3
                    .replace(/^## (.*)$/gm, '<h2>$1</h2>') // Header 2
                    .replace(/^# (.*)$/gm, '<h1>$1</h1>') // Header 1
                    .replace(/\*(.*?)\*/g, '<em>$1</em>') // Italic
                    .replace(/__(.*?)__/g, '<u>$1</u>') // Underline
                    .replace(/~~(.*?)~~/g, '<s>$1</s>') // Strikethrough
                    .replace(/```(.*?)```/gs, '<pre><code>$1</code></pre>') // Code block
                    .replace(/`(.*?)`/g, '<code>$1</code>') // Inline code
                    .replace(/^>(.*?)($|\n)/gm, '<blockquote>$1</blockquote>$2') // Blockquote (only at line start)
                    .replace(/\n/g, '<br>') || ''}
                </div>
            {:else if subcomponent.type == 12}
                <MediaGallery items={subcomponent.items} />
            {:else if subcomponent.type == 13}
                <div class="discord-file-input">
                    <input type="file" disabled />
                </div>
            {:else if subcomponent.type == 14}
                <div class="discord-separator" />
            {:else}
                <div class="unknown-component">
                    Unknown Component Type: {subcomponent.type}
                </div>
            {/if}
        {/each}
    {/if}
</div>
<script>
    export let component = {};
    import ActionRow from "./ActionRow.svelte";
    import Button from "./Button.svelte";
    import MediaGallery from "./MediaGallery.svelte";
    import Section from "./Section.svelte";
    
    function getButtonStyle(style) {
        let buttonStyle = '';
        switch (style) {
            case 1: buttonStyle = "button-primary"; break;
            case 2: buttonStyle = "button-secondary"; break;
            case 3: buttonStyle = "button-success"; break;
            case 4: buttonStyle = "button-danger"; break;
            default: buttonStyle = "button-primary"; break;
        }

        return buttonStyle;
    }
</script>
<style>
    .discord-text-component {
        font-size: 14px;
        line-height: 1.4;
        color: var(--discord-text);
        background-color: rgba(0, 0, 0, 0.1);
        border-radius: 3px;
        padding: 8px 12px;
        margin: 4px 0;
        word-wrap: break-word;
        max-width: 520px;
    }
    
    .component-container {
        background-color: var(--discord-dark);
        border-radius: 4px;
        padding: 12px;
        margin: 4px 0;
        max-width: 520px;
        width: 100%;
    }

    .component-container.spoiler {
        filter: blur(4px);
    }

    .component-container.spoiler:hover {
        filter: none;
    }
    
    .discord-separator {
        height: 1px;
        width: 100%;
        background-color: rgba(79, 84, 92, 0.48);
        margin: 4px 0;
        max-width: 520px;
    }
    .unknown-component {
        border: 1px dashed var(--discord-text-muted);
        border-radius: 3px;
        padding: 8px;
        color: var(--discord-text-muted);
        font-size: 12px;
        font-style: italic;
        margin: 4px 0;
    }
</style>
