// frontend/src/components/AuditLogDiff.svelte
<script>
    export let oldData = null;
    export let newData = null;

    let oldObj = {};
    let newObj = {};

    function safeParse(data) {
        if (!data) return {};
        try {
            const parsed = JSON.parse(data);
            if (parsed === null || parsed === undefined) return {};
            if (Array.isArray(parsed)) return { items: parsed };
            if (typeof parsed !== "object") return { value: parsed };
            return parsed;
        } catch {
            return {};
        }
    }

    $: oldObj = safeParse(oldData);
    $: newObj = safeParse(newData);

    // When both old and new exist, compare only shared keys to avoid
    // noise from mismatched struct types. When only one side exists,
    // show all keys from that side.
    $: hasBoth =
        Object.keys(oldObj).length > 0 && Object.keys(newObj).length > 0;
    $: allKeys = [
        ...new Set([...Object.keys(oldObj), ...Object.keys(newObj)]),
    ].sort();

    function formatValue(val) {
        if (val === null || val === undefined) return "null";
        if (typeof val === "object") return JSON.stringify(val, null, 2);
        return String(val);
    }

    function getChangeType(key) {
        const inOld = key in oldObj;
        const inNew = key in newObj;

        if (inOld && !inNew) return "removed";
        if (!inOld && inNew) return "added";

        const oldVal = JSON.stringify(oldObj[key]);
        const newVal = JSON.stringify(newObj[key]);
        if (oldVal !== newVal) return "changed";

        return "unchanged";
    }

    // When both old and new exist, only show keys in both that changed,
    // plus a summary of unique keys if any. When only one side exists,
    // show all keys.
    $: visibleKeys = hasBoth
        ? allKeys.filter((k) => getChangeType(k) === "changed")
        : allKeys.filter((k) => getChangeType(k) !== "unchanged");

    $: onlyOldKeys = hasBoth
        ? allKeys.filter((k) => k in oldObj && !(k in newObj))
        : [];
    $: onlyNewKeys = hasBoth
        ? allKeys.filter((k) => !(k in oldObj) && k in newObj)
        : [];
    $: hasUniqueKeys = onlyOldKeys.length > 0 || onlyNewKeys.length > 0;

    let showStructuralChanges = false;
</script>

{#if allKeys.length === 0}
    <div class="empty">No data available</div>
{:else}
    <div class="diff-container">
        {#each visibleKeys as key}
            {@const changeType = getChangeType(key)}
            <div class="diff-row {changeType}">
                <span class="diff-key">{key}</span>
                {#if changeType === "removed"}
                    <span class="diff-value removed-value"
                        >{formatValue(oldObj[key])}</span
                    >
                {:else if changeType === "added"}
                    <span class="diff-value added-value"
                        >{formatValue(newObj[key])}</span
                    >
                {:else}
                    <span class="diff-value removed-value"
                        >{formatValue(oldObj[key])}</span
                    >
                    <span class="diff-arrow">-></span>
                    <span class="diff-value added-value"
                        >{formatValue(newObj[key])}</span
                    >
                {/if}
            </div>
        {/each}

        {#if visibleKeys.length === 0}
            <div class="empty">No changes detected</div>
        {/if}

        {#if hasBoth && hasUniqueKeys}
            <button
                class="toggle-structural"
                on:click={() =>
                    (showStructuralChanges = !showStructuralChanges)}
            >
                {showStructuralChanges ? "Hide" : "Show"} structural changes ({onlyOldKeys.length +
                    onlyNewKeys.length} fields)
            </button>
            {#if showStructuralChanges}
                {#each onlyOldKeys as key}
                    <div class="diff-row removed">
                        <span class="diff-key">{key}</span>
                        <span class="diff-value removed-value"
                            >{formatValue(oldObj[key])}</span
                        >
                    </div>
                {/each}
                {#each onlyNewKeys as key}
                    <div class="diff-row added">
                        <span class="diff-key">{key}</span>
                        <span class="diff-value added-value"
                            >{formatValue(newObj[key])}</span
                        >
                    </div>
                {/each}
            {/if}
        {/if}
    </div>
{/if}

<style>
    .diff-container {
        font-family: monospace;
        font-size: 13px;
        line-height: 1.6;
        overflow-x: auto;
        text-align: left !important;
    }

    .diff-row {
        display: flex;
        align-items: flex-start;
        gap: 8px;
        padding: 4px 8px;
        border-radius: 4px;
        margin-bottom: 2px;
    }

    .diff-row.removed {
        background: rgba(227, 93, 106, 0.1);
    }

    .diff-row.added {
        background: rgba(40, 167, 69, 0.1);
    }

    .diff-row.changed {
        background: rgba(153, 93, 243, 0.1);
    }

    .diff-key {
        font-weight: 600;
        min-width: 120px;
        color: var(--text-primary);
    }

    .diff-value {
        word-break: break-all;
        white-space: pre-wrap;
    }

    .removed-value {
        color: #e35d6a;
    }

    .added-value {
        color: #28a745;
    }

    .diff-arrow {
        color: var(--text-secondary, #6c757d);
        flex-shrink: 0;
    }

    .empty {
        color: var(--text-secondary, #6c757d);
        font-style: italic;
        padding: 8px;
    }

    .toggle-structural {
        background: none;
        border: 1px solid var(--text-secondary, #6c757d);
        color: var(--text-secondary, #6c757d);
        padding: 4px 10px;
        border-radius: 4px;
        cursor: pointer;
        font-size: 12px;
        margin-top: 6px;
        margin-bottom: 4px;
    }

    .toggle-structural:hover {
        color: var(--text-primary);
        border-color: var(--text-primary);
    }
</style>

// frontend/src/components/AuditLogDiff.tsx
import type { FC } from "react";
import { useState, useMemo } from "react";
import Button from "@/components/Button";

interface AuditLogDiffProps {
  oldData?: string | null;
  newData?: string | null;
}

function safeParse(data: string | null | undefined): Record<string, unknown> {
  if (!data) return {};
  try {
    const parsed = JSON.parse(data);
    if (parsed === null || parsed === undefined) return {};
    if (Array.isArray(parsed)) return { items: parsed };
    if (typeof parsed !== "object") return { value: parsed };
    return parsed as Record<string, unknown>;
  } catch {
    return {};
  }
}

function formatValue(val: unknown): string {
  if (val === null || val === undefined) return "null";
  if (typeof val === "object") return JSON.stringify(val, null, 2);
  return String(val);
}

type ChangeType = "added" | "removed" | "changed" | "unchanged";

function getChangeType(
  key: string,
  oldObj: Record<string, unknown>,
  newObj: Record<string, unknown>,
): ChangeType {
  const inOld = key in oldObj;
  const inNew = key in newObj;

  if (inOld && !inNew) return "removed";
  if (!inOld && inNew) return "added";

  const oldVal = JSON.stringify(oldObj[key]);
  const newVal = JSON.stringify(newObj[key]);
  if (oldVal !== newVal) return "changed";

  return "unchanged";
}

const AuditLogDiff: FC<AuditLogDiffProps> = ({ oldData, newData }) => {
  const [showStructuralChanges, setShowStructuralChanges] = useState(false);

  const oldObj = useMemo(() => safeParse(oldData), [oldData]);
  const newObj = useMemo(() => safeParse(newData), [newData]);

  const hasBoth = Object.keys(oldObj).length > 0 && Object.keys(newObj).length > 0;
  const allKeys = useMemo(
    () => [...new Set([...Object.keys(oldObj), ...Object.keys(newObj)])].sort(),
    [oldObj, newObj],
  );

  const visibleKeys = useMemo(
    () =>
      hasBoth
        ? allKeys.filter((k) => getChangeType(k, oldObj, newObj) === "changed")
        : allKeys.filter((k) => getChangeType(k, oldObj, newObj) !== "unchanged"),
    [allKeys, hasBoth, oldObj, newObj],
  );

  const onlyOldKeys = useMemo(
    () => (hasBoth ? allKeys.filter((k) => k in oldObj && !(k in newObj)) : []),
    [allKeys, hasBoth, oldObj, newObj],
  );

  const onlyNewKeys = useMemo(
    () => (hasBoth ? allKeys.filter((k) => !(k in oldObj) && k in newObj) : []),
    [allKeys, hasBoth, oldObj, newObj],
  );

  const hasUniqueKeys = onlyOldKeys.length > 0 || onlyNewKeys.length > 0;

  if (allKeys.length === 0) {
    return <div className="text-gray-400 italic px-2">No data available</div>;
  }

  const rowBg = (type: ChangeType) => {
    switch (type) {
      case "removed":
        return "bg-red-500/10";
      case "added":
        return "bg-green-500/10";
      case "changed":
        return "bg-blue-500/10";
      default:
        return "";
    }
  };

  return (
    <div className="font-mono text-[13px] leading-relaxed overflow-x-auto text-left">
      {visibleKeys.map((key) => {
        const changeType = getChangeType(key, oldObj, newObj);
        return (
          <div
            key={key}
            className={`flex items-start gap-2 px-2 py-1 rounded mb-0.5 flex-col md:flex-row ${rowBg(changeType)}`}
          >
            <span className="font-semibold text-white min-w-30 w-full md:w-auto md:mb-0 mb-2">
              {key}
            </span>
            {changeType === "removed" && (
              <span className="text-red-400 break-all whitespace-pre-wrap">
                {formatValue(oldObj[key])}
              </span>
            )}
            {changeType === "added" && (
              <span className="text-green-500 break-all whitespace-pre-wrap">
                {formatValue(newObj[key])}
              </span>
            )}
            {changeType === "changed" && (
              <>
                {/* Desktop: inline layout */}
                <div className="hidden md:contents">
                  <span className="text-red-400 break-all whitespace-pre-wrap">
                    {formatValue(oldObj[key])}
                  </span>
                  <span className="text-gray-400 shrink-0">-&gt;</span>
                  <span className="text-green-500 break-all whitespace-pre-wrap">
                    {formatValue(newObj[key])}
                  </span>
                </div>
                {/* Mobile: side-by-side grid */}
                <div className="grid grid-cols-2 gap-2 w-full md:hidden">
                  <div className="flex flex-col gap-1 min-w-0">
                    <span className="text-[10px] font-bold uppercase tracking-wider text-red-400">
                      Before
                    </span>
                    <span className="text-red-400 wrap-break-word whitespace-pre-wrap text-xs">
                      {formatValue(oldObj[key])}
                    </span>
                  </div>
                  <div className="flex flex-col gap-1 min-w-0">
                    <span className="text-[10px] font-bold uppercase tracking-wider text-green-500">
                      After
                    </span>
                    <span className="text-green-500 wrap-break-word whitespace-pre-wrap text-xs">
                      {formatValue(newObj[key])}
                    </span>
                  </div>
                </div>
              </>
            )}
          </div>
        );
      })}

      {visibleKeys.length === 0 && (
        <div className="text-gray-400 italic px-2">No changes detected</div>
      )}

      {hasBoth && hasUniqueKeys && (
        <>
          <Button
            variant="outline"
            size="sm"
            className="mt-1.5 mb-1"
            title={showStructuralChanges ? "Hide structural changes" : "Show structural changes"}
            onClick={() => setShowStructuralChanges(!showStructuralChanges)}
          >
            {showStructuralChanges ? "Hide" : "Show"} structural changes (
            {onlyOldKeys.length + onlyNewKeys.length} fields)
          </Button>
          {showStructuralChanges && (
            <>
              {onlyOldKeys.map((key) => (
                <div
                  key={key}
                  className={`flex items-start gap-2 px-2 py-1 rounded mb-0.5 flex-row ${rowBg("removed")}`}
                >
                  <span className="font-semibold text-white min-w-20 md:min-w-30">{key}</span>
                  <span className="text-red-400 break-all whitespace-pre-wrap">
                    {formatValue(oldObj[key])}
                  </span>
                </div>
              ))}
              {onlyNewKeys.map((key) => (
                <div
                  key={key}
                  className={`flex items-start gap-2 px-2 py-1 rounded mb-0.5 flex-row ${rowBg("added")}`}
                >
                  <span className="font-semibold text-white min-w-20 md:min-w-30">{key}</span>
                  <span className="text-green-500 break-all whitespace-pre-wrap">
                    {formatValue(newObj[key])}
                  </span>
                </div>
              ))}
            </>
          )}
        </>
      )}
    </div>
  );
};

export default AuditLogDiff;
